In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['John', 'Alice', 'John', 'John'],
    'Salary': [50000, 60000, 70000, 80000]
});

In [3]:
df

   EmpID   Name  Salary
0    101   John   50000
1    102  Alice   60000
2    103   John   70000
3    104   John   80000

In [14]:
df.loc[df['Name']=='John', 'Name'] = 'Jonathan'
first_john = df.loc[df['Name']=='Jonathan'].index[0];

df.loc[first_john, 'Name'] = 'John';

df

   EmpID      Name  Salary
0    101      John   50000
1    102     Alice   60000
2    103  Jonathan   70000
3    104  Jonathan   80000

In [16]:
df.loc[df['EmpID'] == 103, 'Name'] = 'John';
df

   EmpID      Name  Salary
0    101      John   50000
1    102     Alice   60000
2    103      John   70000
3    104  Jonathan   80000

In [19]:
df.rename(index={0: 'A', 2: 'A'}, inplace=True);
print(df);
df.loc['A']

   EmpID      Name  Salary
A    101      John   50000
1    102     Alice   60000
A    103      John   70000
3    104  Jonathan   80000

   EmpID  Name  Salary
A    101  John   50000
A    103  John   70000

In [18]:
df.loc['A']

   EmpID  Name  Salary
A    101  John   50000
A    103  John   70000

In [ ]:
df_emp = pd.read_excel("employee_valuecounts_sorting_dataset.xlsx");
df_emp
emp_each_dept = df_emp['Department'].value_counts();

# Q1 Display the number of employees in each department and identify the department with the highest number of employees.

print("Number of emp in each dept", emp_each_dept);
print(f"{emp_each_dept.index[0]} has highest number of employees i.e {emp_each_dept.iloc[0]}");

Number of emp in each dept Department
IT         9
HR         5
Finance    3
Sales      2
Support    1
Name: count, dtype: int64
9
IT has highest number of employees i.e 9

In [ ]:
# Q2 Display the top 5 highest-paid employees sorted by Salary in descending order.
sorted_sal = df_emp.sort_values(by='Salary',ascending=False);
sorted_sal.iloc[0:5]

    EmpID   Name   Age   Salary Department Country Grade    Status
3     104  David  35.0  80000.0    Finance     USA     A    Active
14    115  David  35.0  80000.0    Finance     USA     A    Active
7     108   Mike  32.0  75000.0    Finance     USA     A  Inactive
9     110    Tom  31.0  70000.0      Sales      UK     B    Active
15    116  Kiran  30.0  70000.0      Sales   India     C  Inactive