In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.DataFrame({'shirt_size':["S","M","S","XL","S","L"]})

# categories = df['shirt_size'].unique().tolist();

oe = OrdinalEncoder(categories=[['S', 'M', 'L', 'XL']]);
df['shirt_size_en'] = oe.fit_transform(df[['shirt_size']]);

df

  shirt_size  shirt_size_en
0          S            0.0
1          M            1.0
2          S            0.0
3         XL            3.0
4          S            0.0
5          L            2.0

In [8]:
df = pd.DataFrame({
    'education': [
        'Graduate',
        'PhD',
        'School',
        'Masters',
        'Graduate'
    ]
});

df['education'].unique().tolist()

categories = ['School', 'Graduate', 'Masters', 'PhD'];

oe = OrdinalEncoder(categories=[categories], dtype=int);
df['education_enc'] = oe.fit_transform(df[['education']]);
df.sort_values(by='education_enc', inplace=True)
df

  education  education_enc
2    School              0
0  Graduate              1
4  Graduate              1
3   Masters              2
1       PhD              3

In [5]:
df = pd.DataFrame({
    'priority': [
        'High',
        'Critical',
        'Low',
        'Medium',
        'High'
    ]
});

categories = ['Low', 'Medium', 'High', 'Critical'];
oe = OrdinalEncoder(categories=[categories]);

df['priority_en'] = oe.fit_transform(df[['priority']]);
df.sort_values(by='priority_en', inplace=True);

df

   priority  priority_en
2       Low          0.0
3    Medium          1.0
0      High          2.0
4      High          2.0
1  Critical          3.0